"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-yf9xaj2*tacht*3^t_jgwz!7z^89etykirf#3e$@le*9d76)8c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


CORS_ALLOW_METHODS = [
    'GET',
    'POST',
    'PUT',
    'PATCH',
    'DELETE',
    'OPTIONS',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'myapp',
    'graphene_django',
    'graphene_file_upload.django',
    'rest_framework',
    'django.contrib.sites',
    'corsheaders',
    'graphql_jwt',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',  # For Google
    'allauth.socialaccount.providers.facebook',  # For Facebook
    'allauth.socialaccount.providers.twitter',  # For Twitter
    'allauth.socialaccount.providers.github',
]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'eventdb',
        'USER': 'postgres',
        'PASSWORD': '1234',
        'HOST': 'localhost',
        'PORT': '5432'
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'limbureubenn@gmail.com'
EMAIL_HOST_PASSWORD = 'bqxg asvo ziey eknt'
DEFAULT_FROM_EMAIL = 'limbureubenn@gmail.com'
# FRONTEND_URL = 'http://localhost:4200'
# BACKEND_URL = 'http://127.0.0.1:8000'
# FRONTEND_URL = 'http://192.168.1.124:4200'
FRONTEND_URL = 'http://192.168.1.124:5173'
BACKEND_URL = 'http://192.168.1.124:8000'



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'

# settings.py
STATICFILES_DIRS = [
    BASE_DIR / "static",
]


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# GRAPHENE = {
#     'SCHEMA': 'myapp.schema.schema'
# }

GRAPHENE = {
    'SCHEMA': 'myapp.schema.schema',  # Adjust with your actual schema path
    'GRAPHIQL': True,  # Make sure this is True
}


MEDIA_URL = "/media/"

MEDIA_ROOT = os.path.join(BASE_DIR, "media")



STATICFILES_DIRS = [
    BASE_DIR / "static",
    'var/www/static',
]



STATIC_ROOT = BASE_DIR / 'staticfiles'  # or '/home/rooben/Desktop/django_second/project/staticfiles'



AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
    'graphql_jwt.backends.JSONWebTokenBackend',
    'django.contrib.auth.backends.ModelBackend',
)

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

GITHUB_CLIENT_ID = 'Ov23li8atSplYkf8MDuh'
GITHUB_CLIENT_SECRET = 'f5b4e2a0902e10140cac7db12eb25ae9c9ea6749'


GRAPHENE = {
    'MIDDLEWARE': [
        'graphql_jwt.middleware.JSONWebTokenMiddleware',
    ],
    'SCHEMA': 'myapp.schema.schema',  # Replace with your schema location
}

import datetime

GRAPHENE_JWT = {
    'JWT_EXPIRATION_DELTA': datetime.timedelta(seconds=10),  # Set token expiration
}


CORS_ALLOW_ALL_ORIGINS = True


PAYPAL_CLIENT_ID = "ASH5PiLWudBqbvHyQSZjYmHLG1tVbUBwr4PP8Lcm2jERxUuDxLI7uVh_IGZ6vQxXHzTTVWxdD-v9Hxqq"
PAYPAL_SECRET_KEY = "EDsfudmCqcMSithjNZL85mHNUuTrigdjW8L5UZmMYda0pUHMcj4upwXeCHOVOmdUTsCOeCnkQ0Nsxhin"
PAYPAL_ENVIRONMENT = "sandbox"

BASE_URL = "http://localhost:5173"


# PAYPAL_CLIENT_ID = 'your-paypal-client-id'
# PAYPAL_CLIENT_SECRET = 'your-paypal-client-secret'
# PAYPAL_API_BASE_URL = 'https://api-m.sandbox.paypal.com'

# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:5173",
#     "http://192.168.52.163:5173",
#     "http://192.168.0.9",
#     "http://192.168.1.124:5173",
#     "http://192.168.240.163"
#     "http://192.168.240.163:5173"
# ]

CORS_ALLOWED_ORIGINS = [
     "http://localhost:5173",
    
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",  # Allow localhost:5173 as trusted origin for CSRF
    "https://localhost:5173",  # Also allow https://localhost:5173 if you're using HTTPS
]

CORS_ALLOW_HEADERS = [
    'content-type',
    'x-csrftoken',
    "content-type",
    "authorization",
]

CSRF_COOKIE_DOMAIN = "localhost"

CORS_ALLOW_CREDENTIALS = True


CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript to access the cookie
CSRF_COOKIE_SECURE = False    # Disable this for local development


CSRF_COOKIE_NAME = 'csrftoken'
CSRF_TRUSTED_ORIGINS = ['http://localhost:5173']  # Add your frontend URL

